version: '3.5'
services:
  ubuntu-20.04-desktop:
    image: ubuntu-20.04-desktop-gnome:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubuntu-desktop
    ports:
      - 5901:5901
      - 6080:6080
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes: 
      - /sys/fs/cgroup:/sys/fs/cgroup 
    cap_add:
      - SYS_BOOT 
      - SYS_ADMIN

    

